// Code generated by 'yaegi extract github.com/siyul-park/uniflow/pkg/testing'. DO NOT EDIT.

package plugin

import (
	"context"
	"github.com/siyul-park/uniflow/pkg/testing"
	"go/constant"
	"go/token"
	"reflect"
)

func init() {
	Symbols["github.com/siyul-park/uniflow/pkg/testing/testing"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"NewErrorReporter": reflect.ValueOf(testing.NewErrorReporter),
		"NewRunner":        reflect.ValueOf(testing.NewRunner),
		"NewTester":        reflect.ValueOf(testing.NewTester),
		"NewTextReporter":  reflect.ValueOf(testing.NewTextReporter),
		"ReportFunc":       reflect.ValueOf(testing.ReportFunc),
		"RunFunc":          reflect.ValueOf(testing.RunFunc),
		"StatusFail":       reflect.ValueOf(constant.MakeFromLiteral("\"FAIL\"", token.STRING, 0)),
		"StatusPass":       reflect.ValueOf(constant.MakeFromLiteral("\"PASS\"", token.STRING, 0)),

		// type definitions
		"ErrorReporter": reflect.ValueOf((*testing.ErrorReporter)(nil)),
		"Reporter":      reflect.ValueOf((*testing.Reporter)(nil)),
		"Reporters":     reflect.ValueOf((*testing.Reporters)(nil)),
		"Result":        reflect.ValueOf((*testing.Result)(nil)),
		"Runner":        reflect.ValueOf((*testing.Runner)(nil)),
		"Suite":         reflect.ValueOf((*testing.Suite)(nil)),
		"Tester":        reflect.ValueOf((*testing.Tester)(nil)),

		// interface wrapper definitions
		"_Reporter": reflect.ValueOf((*_github_com_siyul_park_uniflow_pkg_testing_Reporter)(nil)),
		"_Suite":    reflect.ValueOf((*_github_com_siyul_park_uniflow_pkg_testing_Suite)(nil)),
	}
}

// _github_com_siyul_park_uniflow_pkg_testing_Reporter is an interface wrapper for Reporter type
type _github_com_siyul_park_uniflow_pkg_testing_Reporter struct {
	IValue  interface{}
	WReport func(ctx context.Context, result *testing.Result) error
}

func (W _github_com_siyul_park_uniflow_pkg_testing_Reporter) Report(ctx context.Context, result *testing.Result) error {
	return W.WReport(ctx, result)
}

// _github_com_siyul_park_uniflow_pkg_testing_Suite is an interface wrapper for Suite type
type _github_com_siyul_park_uniflow_pkg_testing_Suite struct {
	IValue interface{}
	WRun   func(t *testing.Tester)
}

func (W _github_com_siyul_park_uniflow_pkg_testing_Suite) Run(t *testing.Tester) {
	W.WRun(t)
}
