// Code generated by 'yaegi extract github.com/gofrs/uuid'. DO NOT EDIT.

package plugin

import (
	"github.com/gofrs/uuid"
	"go/constant"
	"go/token"
	"reflect"
)

func init() {
	Symbols["github.com/gofrs/uuid/uuid"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"DefaultGenerator":  reflect.ValueOf(&uuid.DefaultGenerator).Elem(),
		"DomainGroup":       reflect.ValueOf(constant.MakeFromLiteral("1", token.INT, 0)),
		"DomainOrg":         reflect.ValueOf(constant.MakeFromLiteral("2", token.INT, 0)),
		"DomainPerson":      reflect.ValueOf(constant.MakeFromLiteral("0", token.INT, 0)),
		"FromBytes":         reflect.ValueOf(uuid.FromBytes),
		"FromBytesOrNil":    reflect.ValueOf(uuid.FromBytesOrNil),
		"FromString":        reflect.ValueOf(uuid.FromString),
		"FromStringOrNil":   reflect.ValueOf(uuid.FromStringOrNil),
		"Must":              reflect.ValueOf(uuid.Must),
		"NamespaceDNS":      reflect.ValueOf(&uuid.NamespaceDNS).Elem(),
		"NamespaceOID":      reflect.ValueOf(&uuid.NamespaceOID).Elem(),
		"NamespaceURL":      reflect.ValueOf(&uuid.NamespaceURL).Elem(),
		"NamespaceX500":     reflect.ValueOf(&uuid.NamespaceX500).Elem(),
		"NewGen":            reflect.ValueOf(uuid.NewGen),
		"NewGenWithHWAF":    reflect.ValueOf(uuid.NewGenWithHWAF),
		"NewGenWithOptions": reflect.ValueOf(uuid.NewGenWithOptions),
		"NewV1":             reflect.ValueOf(uuid.NewV1),
		"NewV3":             reflect.ValueOf(uuid.NewV3),
		"NewV4":             reflect.ValueOf(uuid.NewV4),
		"NewV5":             reflect.ValueOf(uuid.NewV5),
		"NewV6":             reflect.ValueOf(uuid.NewV6),
		"NewV7":             reflect.ValueOf(uuid.NewV7),
		"Nil":               reflect.ValueOf(&uuid.Nil).Elem(),
		"Size":              reflect.ValueOf(constant.MakeFromLiteral("16", token.INT, 0)),
		"TimestampFromV1":   reflect.ValueOf(uuid.TimestampFromV1),
		"TimestampFromV6":   reflect.ValueOf(uuid.TimestampFromV6),
		"V1":                reflect.ValueOf(uuid.V1),
		"V3":                reflect.ValueOf(uuid.V3),
		"V4":                reflect.ValueOf(uuid.V4),
		"V5":                reflect.ValueOf(uuid.V5),
		"V6":                reflect.ValueOf(uuid.V6),
		"V7":                reflect.ValueOf(uuid.V7),
		"VariantFuture":     reflect.ValueOf(uuid.VariantFuture),
		"VariantMicrosoft":  reflect.ValueOf(uuid.VariantMicrosoft),
		"VariantNCS":        reflect.ValueOf(uuid.VariantNCS),
		"VariantRFC4122":    reflect.ValueOf(uuid.VariantRFC4122),
		"WithEpochFunc":     reflect.ValueOf(uuid.WithEpochFunc),
		"WithHWAddrFunc":    reflect.ValueOf(uuid.WithHWAddrFunc),
		"WithRandomReader":  reflect.ValueOf(uuid.WithRandomReader),

		// type definitions
		"EpochFunc":  reflect.ValueOf((*uuid.EpochFunc)(nil)),
		"Gen":        reflect.ValueOf((*uuid.Gen)(nil)),
		"GenOption":  reflect.ValueOf((*uuid.GenOption)(nil)),
		"Generator":  reflect.ValueOf((*uuid.Generator)(nil)),
		"HWAddrFunc": reflect.ValueOf((*uuid.HWAddrFunc)(nil)),
		"NullUUID":   reflect.ValueOf((*uuid.NullUUID)(nil)),
		"Timestamp":  reflect.ValueOf((*uuid.Timestamp)(nil)),
		"UUID":       reflect.ValueOf((*uuid.UUID)(nil)),

		// interface wrapper definitions
		"_Generator": reflect.ValueOf((*_github_com_gofrs_uuid_Generator)(nil)),
	}
}

// _github_com_gofrs_uuid_Generator is an interface wrapper for Generator type
type _github_com_gofrs_uuid_Generator struct {
	IValue interface{}
	WNewV1 func() (uuid.UUID, error)
	WNewV3 func(ns uuid.UUID, name string) uuid.UUID
	WNewV4 func() (uuid.UUID, error)
	WNewV5 func(ns uuid.UUID, name string) uuid.UUID
	WNewV6 func() (uuid.UUID, error)
	WNewV7 func() (uuid.UUID, error)
}

func (W _github_com_gofrs_uuid_Generator) NewV1() (uuid.UUID, error) {
	return W.WNewV1()
}
func (W _github_com_gofrs_uuid_Generator) NewV3(ns uuid.UUID, name string) uuid.UUID {
	return W.WNewV3(ns, name)
}
func (W _github_com_gofrs_uuid_Generator) NewV4() (uuid.UUID, error) {
	return W.WNewV4()
}
func (W _github_com_gofrs_uuid_Generator) NewV5(ns uuid.UUID, name string) uuid.UUID {
	return W.WNewV5(ns, name)
}
func (W _github_com_gofrs_uuid_Generator) NewV6() (uuid.UUID, error) {
	return W.WNewV6()
}
func (W _github_com_gofrs_uuid_Generator) NewV7() (uuid.UUID, error) {
	return W.WNewV7()
}
