// Code generated by 'yaegi extract github.com/siyul-park/uniflow/pkg/symbol'. DO NOT EDIT.

package plugin

import (
	"github.com/siyul-park/uniflow/pkg/symbol"
	"reflect"
)

func init() {
	Symbols["github.com/siyul-park/uniflow/pkg/symbol/symbol"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"LoadFunc":           reflect.ValueOf(symbol.LoadFunc),
		"LoadListenerHook":   reflect.ValueOf(symbol.LoadListenerHook),
		"NewCluster":         reflect.ValueOf(symbol.NewCluster),
		"NewTable":           reflect.ValueOf(symbol.NewTable),
		"UnloadFunc":         reflect.ValueOf(symbol.UnloadFunc),
		"UnloadListenerHook": reflect.ValueOf(symbol.UnloadListenerHook),

		// type definitions
		"Cluster":        reflect.ValueOf((*symbol.Cluster)(nil)),
		"LoadHook":       reflect.ValueOf((*symbol.LoadHook)(nil)),
		"LoadHooks":      reflect.ValueOf((*symbol.LoadHooks)(nil)),
		"LoadListener":   reflect.ValueOf((*symbol.LoadListener)(nil)),
		"Symbol":         reflect.ValueOf((*symbol.Symbol)(nil)),
		"Table":          reflect.ValueOf((*symbol.Table)(nil)),
		"TableOption":    reflect.ValueOf((*symbol.TableOption)(nil)),
		"UnloadHook":     reflect.ValueOf((*symbol.UnloadHook)(nil)),
		"UnloadHooks":    reflect.ValueOf((*symbol.UnloadHooks)(nil)),
		"UnloadListener": reflect.ValueOf((*symbol.UnloadListener)(nil)),

		// interface wrapper definitions
		"_LoadHook":       reflect.ValueOf((*_github_com_siyul_park_uniflow_pkg_symbol_LoadHook)(nil)),
		"_LoadListener":   reflect.ValueOf((*_github_com_siyul_park_uniflow_pkg_symbol_LoadListener)(nil)),
		"_UnloadHook":     reflect.ValueOf((*_github_com_siyul_park_uniflow_pkg_symbol_UnloadHook)(nil)),
		"_UnloadListener": reflect.ValueOf((*_github_com_siyul_park_uniflow_pkg_symbol_UnloadListener)(nil)),
	}
}

// _github_com_siyul_park_uniflow_pkg_symbol_LoadHook is an interface wrapper for LoadHook type
type _github_com_siyul_park_uniflow_pkg_symbol_LoadHook struct {
	IValue interface{}
	WLoad  func(a0 *symbol.Symbol) error
}

func (W _github_com_siyul_park_uniflow_pkg_symbol_LoadHook) Load(a0 *symbol.Symbol) error {
	return W.WLoad(a0)
}

// _github_com_siyul_park_uniflow_pkg_symbol_LoadListener is an interface wrapper for LoadListener type
type _github_com_siyul_park_uniflow_pkg_symbol_LoadListener struct {
	IValue interface{}
	WLoad  func(a0 symbol.LoadHook) error
}

func (W _github_com_siyul_park_uniflow_pkg_symbol_LoadListener) Load(a0 symbol.LoadHook) error {
	return W.WLoad(a0)
}

// _github_com_siyul_park_uniflow_pkg_symbol_UnloadHook is an interface wrapper for UnloadHook type
type _github_com_siyul_park_uniflow_pkg_symbol_UnloadHook struct {
	IValue  interface{}
	WUnload func(a0 *symbol.Symbol) error
}

func (W _github_com_siyul_park_uniflow_pkg_symbol_UnloadHook) Unload(a0 *symbol.Symbol) error {
	return W.WUnload(a0)
}

// _github_com_siyul_park_uniflow_pkg_symbol_UnloadListener is an interface wrapper for UnloadListener type
type _github_com_siyul_park_uniflow_pkg_symbol_UnloadListener struct {
	IValue  interface{}
	WUnload func(a0 symbol.UnloadHook) error
}

func (W _github_com_siyul_park_uniflow_pkg_symbol_UnloadListener) Unload(a0 symbol.UnloadHook) error {
	return W.WUnload(a0)
}
