// Code generated by 'yaegi extract github.com/siyul-park/uniflow/pkg/port'. DO NOT EDIT.

package plugin

import (
	"github.com/siyul-park/uniflow/pkg/port"
	"github.com/siyul-park/uniflow/pkg/process"
	"reflect"
)

func init() {
	Symbols["github.com/siyul-park/uniflow/pkg/port/port"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"CloseHookFunc": reflect.ValueOf(port.CloseHookFunc),
		"ListenFunc":    reflect.ValueOf(port.ListenFunc),
		"NewIn":         reflect.ValueOf(port.NewIn),
		"NewOut":        reflect.ValueOf(port.NewOut),
		"OpenHookFunc":  reflect.ValueOf(port.OpenHookFunc),
		"Pipe":          reflect.ValueOf(port.Pipe),

		// type definitions
		"CloseHook":  reflect.ValueOf((*port.CloseHook)(nil)),
		"CloseHooks": reflect.ValueOf((*port.CloseHooks)(nil)),
		"InPort":     reflect.ValueOf((*port.InPort)(nil)),
		"Listener":   reflect.ValueOf((*port.Listener)(nil)),
		"Listeners":  reflect.ValueOf((*port.Listeners)(nil)),
		"OpenHook":   reflect.ValueOf((*port.OpenHook)(nil)),
		"OpenHooks":  reflect.ValueOf((*port.OpenHooks)(nil)),
		"OutPort":    reflect.ValueOf((*port.OutPort)(nil)),

		// interface wrapper definitions
		"_CloseHook": reflect.ValueOf((*_github_com_siyul_park_uniflow_pkg_port_CloseHook)(nil)),
		"_Listener":  reflect.ValueOf((*_github_com_siyul_park_uniflow_pkg_port_Listener)(nil)),
		"_OpenHook":  reflect.ValueOf((*_github_com_siyul_park_uniflow_pkg_port_OpenHook)(nil)),
	}
}

// _github_com_siyul_park_uniflow_pkg_port_CloseHook is an interface wrapper for CloseHook type
type _github_com_siyul_park_uniflow_pkg_port_CloseHook struct {
	IValue interface{}
	WClose func()
}

func (W _github_com_siyul_park_uniflow_pkg_port_CloseHook) Close() {
	W.WClose()
}

// _github_com_siyul_park_uniflow_pkg_port_Listener is an interface wrapper for Listener type
type _github_com_siyul_park_uniflow_pkg_port_Listener struct {
	IValue  interface{}
	WAccept func(proc *process.Process)
}

func (W _github_com_siyul_park_uniflow_pkg_port_Listener) Accept(proc *process.Process) {
	W.WAccept(proc)
}

// _github_com_siyul_park_uniflow_pkg_port_OpenHook is an interface wrapper for OpenHook type
type _github_com_siyul_park_uniflow_pkg_port_OpenHook struct {
	IValue interface{}
	WOpen  func(a0 *process.Process)
}

func (W _github_com_siyul_park_uniflow_pkg_port_OpenHook) Open(a0 *process.Process) {
	W.WOpen(a0)
}
