// Code generated by 'yaegi extract github.com/siyul-park/uniflow/pkg/encoding'. DO NOT EDIT.

package plugin

import (
	"github.com/siyul-park/uniflow/pkg/encoding"
	"reflect"
)

func init() {
	Symbols["github.com/siyul-park/uniflow/pkg/encoding/encoding"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"ErrUnsupportedType":  reflect.ValueOf(&encoding.ErrUnsupportedType).Elem(),
		"ErrUnsupportedValue": reflect.ValueOf(&encoding.ErrUnsupportedValue).Elem(),
	}
}
