- kind: listener
  name: listener
  protocol: http
  port: 8000
  links:
    out:
      - name: logging
        port: in

- kind: block
  name: logging
  specs:
    - kind: fork
    - kind: write
      filename: /dev/stdout
